Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: Main.lambda_function.lambda_handler
      CodeUri: Main
      Runtime: python3.11
