AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload-envelope-attachments-zohocrm-box
      CodeUri: Main
      Description: Upload Envelope related to Zoho CRM documents to Box
      MemorySize: 1024
      Timeout: 30
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Layers:
        - arn:aws:lambda:sa-east-1:831104378922:layer:docusign-esingPython:2
